### PR TITLE
Updated Readme with examples.

### PR DESCRIPTION
**Pull request by Dibbyo456**

### CODE REVIEW

**Comment by baileyherbert** [comment]
Thanks again. I will release this on Packagist shortly after a couple small tweaks.

**Comment by Dibbyo456** [comment]
That is very good hear. 😊 Although I've not tested it with **PHP 7.3**, assuming it's gonna work without any issue. Will let you know if run into some.

**Comment by baileyherbert** [comment]
No worries. There was a small issue with the usage of the hyphen (`item-version`), but I switched it to `item_version` instead -- see updated [`readme.md`](https://github.com/baileyherbert/envato.php/blob/49d82bd790f5e4e2e240f0fe9dcb3ad5204a0785/README.md#look-up-a-single-wordpress-themeplugin-version).

**Comment by Dibbyo456** [comment]
@baileyherbert Hi, I have two question.

> This client does not disable SSL. It ships with a Certificate Authority bundle and uses this bundle to verify the Envato API's SSL certificate, instead of relying on the system's often-unavailable certificate.

1) Does it slow down requests time?
2) Does the certificate expire after certain period of time?

**Comment by baileyherbert** [comment]
I believe I ship the CA bundle from Haxx: https://curl.haxx.se/docs/caextract.html
This was my way of ensuring that the library would continue to function even if Envato changed their SSL to a completely different certificate root. Right now they're using the DigiCert Baltimore CyberTrust root.

1. There will indeed be a performance impact, as CURL will read through the bundled root certificates in order to find whether the connection with Envato is trustworthy. The impact should be minimal (< 10 ms).

2. Yes, but this isn't an issue for us. The Baltimore CyberTrust Root has an expiration date of [12/May/2025](https://www.digicert.com/digicert-root-certificates.htm). However, Envato will be forced to switch to a new root certificate before then, which is likely already included in our CA bundle.

**Pull request merged**
